version: '3.1'
services:
  app:
    build: .
    volumes:
     - ./:/app
     - /app/node_modules
    ports:
      - 6005:8000
  nginx:
    image: nginx
    ports:
      - 6006:80
    links:
      - app:authhost
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf